name: uniperceiver
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9.17
  - pip
  - pip:
    - av==9.0.0
    - einops==0.4.1
    - ftfy==6.1.1
    - fvcore==0.1.5.post20220305
    - h5py==3.6.0
    - hjson==3.0.2
    - huggingface-hub==0.6.0
    - hydra-core==1.1.2
    - iopath==0.1.9
    - jsonlines==3.0.0
    - matplotlib==3.5.1
    - ninja==1.10.2.3
    - omegaconf==2.1.2
    - opencv-python==4.5.5.64
    - pandas==1.3.5
    - panopticapi @ git+https://github.com/cocodataset/panopticapi.git@7bb4655548f98f3fedc07bf37e9040a992b054b0
    - Pillow==9.0.1
    - pyarrow==7.0.0
    - pycocoevalcap==1.2
    - pytorch-transformers==1.2.0
    - PyYAML==6.0
    - scikit-learn==1.0.2
    - scipy==1.7.3
    - sklearn==0.0
    - tensorboard==2.8.0
    - timm==0.4.5
    - tqdm==4.63.0
    - transformers==4.19.1
    - cloudpickle
    - protobuf==3.19
    - gdown==4.7.1
    - nvidia-cublas-cu11==11.10.3.66
    - nvidia-cuda-cupti-cu11==11.7.101
    - nvidia-cuda-nvrtc-cu11==11.7.99
    - nvidia-cuda-runtime-cu11==11.7.99
    - nvidia-cudnn-cu11==8.5.0.96
    - nvidia-cufft-cu11==10.9.0.58
    - nvidia-curand-cu11==10.2.10.91
    - nvidia-cusolver-cu11==11.4.0.1
    - nvidia-cusparse-cu11==11.7.4.91
    - nvidia-nccl-cu11==2.14.3
    - nvidia-nvtx-cu11==11.7.91
    - triton==2.0.0
    - cmake==3.27.0
    - boto3==1.28.16
    - botocore==1.31.16
    - fancycompleter==0.9.1
    - Pygments==2.15.1
    - pyrepl==0.9.0
    - sympy==1.12
    - wmctrl==0.4
    - torch==2.0.1
